export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAILURE = "USER_SIGNIN_FAILURE";

export const GET_CANDIDATE_REQUEST = "GET_CANDIDATE_REQUEST";
export const GET_CANDIDATE_SUCCESS = "GET_CANDIDATE_SUCCESS";
export const GET_CANDIDATE_FAILURE = "GET_CANDIDATE_FAILURE";

export const GET_TECHNOLOGY_REQUEST = "GET_TECHNOLOGY_REQUEST";
export const GET_TECHNOLOGY_SUCCESS = "GET_TECHNOLOGY_SUCCESS";
export const GET_TECHNOLOGY_FAILURE = "GET_TECHNOLOGY_FAILURE";


export const GET_COURSE_LIST_REQUEST ="GET_COURSE_LIST_REQUEST";
export const GET_COURSE_LIST_SUCCESS ="GET_COURSE_LIST_SUCCESS";
export const GET_COURSE_LIST_FAILURE ="GET_COURSE_LIST_FAILURE";



export const GET_VIEW_COURSE_REQUEST ="GET_VIEW_COURSE_REQUEST";
export const GET_VIEW_COURSE_SUCCESS ="GET_VIEW_COURSE_SUCCESS";
export const GET_VIEW_COURSE_FAILURE ="GET_VIEW_COURSE_FAILURE";

export const GET_SINGLE_CANDIDATE_REQUEST = "GET_SINGLE_CANDIDATE_REQUEST";
export const GET_SINGLE_CANDIDATE_SUCCESS = "GET_SINGLE_CANDIDATE_SUCCESS";
export const GET_SINGLE_CANDIDATE_FAILURE = "GET_SINGLE_CANDIDATE_FAILURE";

export const DELETE_CANDIDATE_REQUEST ="DELETE_CANDIDATE_REQUEST";
export const DELETE_CANDIDATE_SUCCESS ="DELETE_CANDIDATE_SUCCESS";
export const DELETE_CANDIDATE_FAILURE ="DELETE_CANDIDATE_FAILURE";

export const POST_ADD_CANDIDATE_REQUEST = "POST_ADD_CANDIDATE_REQUEST";
export const POST_ADD_CANDIDATE_SUCCESS = "POST_ADD_CANDIDATE_SUCCESS";
export const POST_ADD_CANDIDATE_FAILURE = "POST_ADD_CANDIDATE_FAILURE";


export const POST_ADD_COURSE_COMMENT_REQUEST = "POST_ADD_COURSE_COMMENT_REQUEST";
export const POST_ADD_COURSE_COMMENT_SUCCESS = "POST_ADD_COURSE_COMMENT_SUCCESS";
export const POST_ADD_COURSE_COMMENT_FAILURE = "POST_ADD_COURSE_COMMENT_FAILURE";


export const POST_ADD_TECHNOLOGY_REQUEST = "POST_ADD_TECHNOLOGY_REQUEST";
export const POST_ADD_TECHNOLOGY_SUCCESS = "POST_ADD_TECHNOLOGY_SUCCESS";
export const POST_ADD_TECHNOLOGY_FAILURE = "POST_ADD_TECHNOLOGY_FAILURE";

